### PR TITLE
Qhala's logo

### PR DESCRIPTION
**Pull request by GraceKiarie**
Added qhala's logo to the sponsors section

@manuelgeek please review and merge

### CODE REVIEW

**Comment by MidigoF** [comment]
@okothkongo kindly verify if the logo has been added to the correct tier.

**Comment by okothkongo** [comment]
> @okothkongo kindly verify if the logo has been added to the correct tier.

@GraceKiarie this good kindly out the sponsor under Conference Supporter Sponsors tier

**Review by okothkongo — COMMENTED** [review]
@GraceKiarie it's great the tier is also that need changing to this section Conference Supporter Sponsors

**Review by manuelgeek — COMMENTED** [review]
ok

**Review by manuelgeek — APPROVED** [review]
ok

**Pull request merged**
