### PR TITLE
add tickets section

### PR DESCRIPTION
**Pull request by MidigoF**
Peek 2021-03-12 11-01

### CODE REVIEW

**Comment by MidigoF** [comment]
Kindly verify that the contents in the ticket cards are okay @sigu @GettyOrawo @manuelgeek @kyendereta @kamalogudah @okothkongo

**Comment by manuelgeek** [comment]
@MidigoF kindly make the cards to be in one row, you remove the sold out one it it's sold out

**Comment by MidigoF** [comment]
> @MidigoF kindly make the cards to be in one row, you remove the sold out one it it's sold out

I insist on having it there so that people can know that it existed

**Comment by kyendereta** [comment]
This looks good @MidigoF . However, I don't see the donation card

**Review by sigu — APPROVED** [review]

**Pull request merged**
